[eqwalizer]
ignore_modules = [
    "opentelemetry_zipkin_pb",
    "opentelemetry_exporter_logs_service_pb",
    "opentelemetry_exporter_metrics_service_pb",
    "opentelemetry_exporter_trace_service_pb",
    "opentelemetry_logs_service",
    "opentelemetry_metrics_service",
    "opentelemetry_trace_service",
]
