version: "3"
services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.155.0@sha256:4935caa35e9a4cb387e35732e8fb22b2b5759af8d12e7043357f03837f6e8df5
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./config/otel-collector-config.yaml:/conf/otel-collector-config.yaml
    links:
      - zipkin

  zipkin:
    image: openzipkin/zipkin-slim:3.6.1@sha256:fc29b9862c14f4fc241cf0259c585e1cfd4e9b18f01ad36d86adaabb7d01815c
    ports:
      - 9411:9411
    privileged: true

  jaeger-all-in-one:
    image: jaegertracing/jaeger:2.20.0@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8
    ports:
      - "16686:16686"
