defmodule OpenTelemetry.SemConv.Incubating.AZAttributes do
  # This is an auto-generated file
  @moduledoc """
  OpenTelemetry Semantic Conventions for AZ attributes.
  """

  @doc """
  [Azure Resource Provider Namespace](https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers) as recognized by the client.

  ### Value type

  Value must be of type `atom() | String.t()`.
  ### Examples

  ```
  ["Microsoft.Storage", "Microsoft.KeyVault", "Microsoft.ServiceBus"]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.AZAttributes.az_namespace()
      :"az.namespace"

  ### Erlang

  ```erlang
  ?AZ_NAMESPACE.
  'az.namespace'
  ```

  <!-- tabs-close -->
  """
  @spec az_namespace :: :"az.namespace"
  def az_namespace do
    :"az.namespace"
  end

  @doc """
  The unique identifier of the service request. It's generated by the Azure service and returned with the response.
  ### Value type

  Value must be of type `atom() | String.t()`.
  ### Examples

  ```
  ["00000000-0000-0000-0000-000000000000"]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.AZAttributes.az_service_request_id()
      :"az.service_request_id"

  ### Erlang

  ```erlang
  ?AZ_SERVICE_REQUEST_ID.
  'az.service_request_id'
  ```

  <!-- tabs-close -->
  """
  @spec az_service_request_id :: :"az.service_request_id"
  def az_service_request_id do
    :"az.service_request_id"
  end
end
