defmodule OpenTelemetry.SemConv.Incubating.PprofAttributes do
  # This is an auto-generated file
  @moduledoc """
  OpenTelemetry Semantic Conventions for Pprof attributes.
  """

  @doc """
  Provides an indication that multiple symbols map to this location's address, for example due to identical code folding by the linker. In that case the line information represents one of the multiple symbols. This field must be recomputed when the symbolization state of the profile changes.

  ### Value type

  Value must be of type `boolean()`.

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_location_is_folded()
      :"pprof.location.is_folded"

  ### Erlang

  ```erlang
  ?PPROF_LOCATION_IS_FOLDED.
  'pprof.location.is_folded'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_location_is_folded :: :"pprof.location.is_folded"
  def pprof_location_is_folded do
    :"pprof.location.is_folded"
  end

  @doc """
  Indicates that there are filenames related to this mapping.

  ### Value type

  Value must be of type `boolean()`.

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_mapping_has_filenames()
      :"pprof.mapping.has_filenames"

  ### Erlang

  ```erlang
  ?PPROF_MAPPING_HAS_FILENAMES.
  'pprof.mapping.has_filenames'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_mapping_has_filenames :: :"pprof.mapping.has_filenames"
  def pprof_mapping_has_filenames do
    :"pprof.mapping.has_filenames"
  end

  @doc """
  Indicates that there are functions related to this mapping.

  ### Value type

  Value must be of type `boolean()`.

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_mapping_has_functions()
      :"pprof.mapping.has_functions"

  ### Erlang

  ```erlang
  ?PPROF_MAPPING_HAS_FUNCTIONS.
  'pprof.mapping.has_functions'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_mapping_has_functions :: :"pprof.mapping.has_functions"
  def pprof_mapping_has_functions do
    :"pprof.mapping.has_functions"
  end

  @doc """
  Indicates that there are inline frames related to this mapping.

  ### Value type

  Value must be of type `boolean()`.

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_mapping_has_inline_frames()
      :"pprof.mapping.has_inline_frames"

  ### Erlang

  ```erlang
  ?PPROF_MAPPING_HAS_INLINE_FRAMES.
  'pprof.mapping.has_inline_frames'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_mapping_has_inline_frames :: :"pprof.mapping.has_inline_frames"
  def pprof_mapping_has_inline_frames do
    :"pprof.mapping.has_inline_frames"
  end

  @doc """
  Indicates that there are line numbers related to this mapping.

  ### Value type

  Value must be of type `boolean()`.

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_mapping_has_line_numbers()
      :"pprof.mapping.has_line_numbers"

  ### Erlang

  ```erlang
  ?PPROF_MAPPING_HAS_LINE_NUMBERS.
  'pprof.mapping.has_line_numbers'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_mapping_has_line_numbers :: :"pprof.mapping.has_line_numbers"
  def pprof_mapping_has_line_numbers do
    :"pprof.mapping.has_line_numbers"
  end

  @doc """
  Free-form text associated with the profile. This field should not be used to store any machine-readable information, it is only for human-friendly content.

  ### Value type

  Value must be of type `[atom() | String.t()]`.
  ### Examples

  ```
  [["hello world", "bazinga"]]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_profile_comment()
      :"pprof.profile.comment"

  ### Erlang

  ```erlang
  ?PPROF_PROFILE_COMMENT.
  'pprof.profile.comment'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_profile_comment :: :"pprof.profile.comment"
  def pprof_profile_comment do
    :"pprof.profile.comment"
  end

  @doc """
  Documentation link for this profile type.

  ### Value type

  Value must be of type `atom() | String.t()`.
  ### Notes

  The URL must be absolute and may be missing if the profile was generated by code that did not supply a link

  ### Examples

  ```
  ["http://pprof.example.com/cpu-profile.html"]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_profile_doc_url()
      :"pprof.profile.doc_url"

  ### Erlang

  ```erlang
  ?PPROF_PROFILE_DOC_URL.
  'pprof.profile.doc_url'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_profile_doc_url :: :"pprof.profile.doc_url"
  def pprof_profile_doc_url do
    :"pprof.profile.doc_url"
  end

  @doc """
  Frames with Function.function_name fully matching the regexp will be dropped from the samples, along with their successors.

  ### Value type

  Value must be of type `atom() | String.t()`.
  ### Examples

  ```
  ["/foobar/"]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_profile_drop_frames()
      :"pprof.profile.drop_frames"

  ### Erlang

  ```erlang
  ?PPROF_PROFILE_DROP_FRAMES.
  'pprof.profile.drop_frames'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_profile_drop_frames :: :"pprof.profile.drop_frames"
  def pprof_profile_drop_frames do
    :"pprof.profile.drop_frames"
  end

  @doc """
  Frames with Function.function_name fully matching the regexp will be kept, even if it matches drop_frames.

  ### Value type

  Value must be of type `atom() | String.t()`.
  ### Examples

  ```
  ["/bazinga/"]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_profile_keep_frames()
      :"pprof.profile.keep_frames"

  ### Erlang

  ```erlang
  ?PPROF_PROFILE_KEEP_FRAMES.
  'pprof.profile.keep_frames'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_profile_keep_frames :: :"pprof.profile.keep_frames"
  def pprof_profile_keep_frames do
    :"pprof.profile.keep_frames"
  end

  @doc """
  Records the pprof's default_sample_type in the original profile. Not set if the default sample type was missing.

  ### Value type

  Value must be of type `atom() | String.t()`.
  ### Notes

  This attribute, if present, **MUST** be set at the scope level (resource_profiles[].scope_profiles[].scope.attributes[]).

  ### Examples

  ```
  ["cpu"]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_scope_default_sample_type()
      :"pprof.scope.default_sample_type"

  ### Erlang

  ```erlang
  ?PPROF_SCOPE_DEFAULT_SAMPLE_TYPE.
  'pprof.scope.default_sample_type'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_scope_default_sample_type :: :"pprof.scope.default_sample_type"
  def pprof_scope_default_sample_type do
    :"pprof.scope.default_sample_type"
  end

  @doc """
  Records the indexes of the sample types in the original profile.

  ### Value type

  Value must be of type `[integer()]`.
  ### Notes

  This attribute, if present, **MUST** be set at the scope level (resource_profiles[].scope_profiles[].scope.attributes[]).

  ### Examples

  ```
  [[3, 0, 1, 2]]
  ```

  <!-- tabs-open -->

  ### Elixir

      iex> OpenTelemetry.SemConv.Incubating.PprofAttributes.pprof_scope_sample_type_order()
      :"pprof.scope.sample_type_order"

  ### Erlang

  ```erlang
  ?PPROF_SCOPE_SAMPLE_TYPE_ORDER.
  'pprof.scope.sample_type_order'
  ```

  <!-- tabs-close -->
  """
  @spec pprof_scope_sample_type_order :: :"pprof.scope.sample_type_order"
  def pprof_scope_sample_type_order do
    :"pprof.scope.sample_type_order"
  end
end
