name: Common Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  erlang_tests:
    name: OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['23.0.2', '22.3.4.2', '21.3.8.16']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.0.0
      with:
        otp-version: ${{ matrix.otp_version }}


    - name: Compile
      run: rebar3 compile
    - name: EUnit tests
      run: rebar3 eunit
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: XRef
      run: rebar3 xref
    - name: Covertool
      run: rebar3 covertool generate
    - uses: codecov/codecov-action@v1
      with:
        file: _build/test/covertool/opentelemetry.covertool.xml

  elixir_tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp_version}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp_version: ['23.0.2', '22.3.4.2', '21.3.8.16']
        elixir: ['1.10.4']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - uses: actions/cache@v1
        with:
          path: _build
          key: build-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock', matrix.otp_version, matrix.elixir)) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix test
      - run: mix dialyzer
