name: Elixir

on:
  pull_request:
    branches:
      - "main"
    types: [opened, reopened, synchronize, labeled]

  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: "27.2.4"
          elixir-version: "1.18.1"
          version-type: "strict"
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        name: Cache
        with:
          path: |
            apps/opentelemetry_api/deps
          key: v3-${{ hashFiles('apps/opentelemetry_api/mix.lock') }}
      - run: mix format --check-formatted
      - run: mix deps.get
        working-directory: apps/opentelemetry_api/
      - run: mix format --check-formatted
        working-directory: apps/opentelemetry_api/
  sdk_tests:
    runs-on: ${{ matrix.os }}
    name: Test SDK on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ["27.2.4", "26.2.5.21"]
        elixir_version: ["1.18.1", "1.14.5"]
        rebar3_version: ["3.24.0"]
        os: [ubuntu-24.04]
        exclude:
          - elixir_version: "1.14.5"
          - otp_version: "27.2.4"
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}
          rebar3-version: ${{ matrix.rebar3_version }}
          version-type: "strict"
      - name: Compile
        run: rebar3 as test compile
      - name: ExUnit
        run: mix test --no-start test/otel_tests.exs test/otel_metric_tests.exs

  api_tests:
    runs-on: ${{ matrix.os }}
    name: Test API on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ["27.2.4", "26.2.5.21"]
        elixir_version: ["1.18.1", "1.14.5"]
        rebar3_version: ["3.24.0"]
        os: [ubuntu-24.04]
        exclude:
          - elixir_version: "1.14.5"
          - otp_version: "27.2.4"
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir_version }}
    defaults:
      run:
        working-directory: apps/opentelemetry_api/
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}
          rebar3-version: ${{ matrix.rebar3_version }}
          version-type: "strict"
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        name: Cache
        with:
          path: |
            apps/opentelemetry_api/deps
            apps/opentelemetry_api/_build
          key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-v4-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/opentelemetry_api/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-
      - run: mix deps.get
        name: Deps
      - run: mix test --cover
        name: ExUnit
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ always() }}
        with:
          file: apps/opentelemetry_api/coverage.xml
          env_vars: OTP_VERSION,ELIXIR_VERSION
          flags: api,elixir

  dialyze:
    runs-on: ${{ matrix.os }}
    name: Dialyze on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ["27.2.4"]
        elixir_version: ["1.18.1"]
        rebar3_version: ["3.24.0"]
        os: [ubuntu-24.04]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir_version }}
    defaults:
      run:
        working-directory: apps/opentelemetry_api/
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}
          version-type: "strict"
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        name: Cache
        with:
          path: |
            apps/opentelemetry_api/deps
            apps/opentelemetry_api/_build
          key: ${{ runner.os }}-dialyzer-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-v4-${{ hashFiles('apps/opentelemetry_api/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-
      - run: mix deps.get
        name: Deps
      - run: mix dialyzer
        name: Dialyzer

  semconv_tests:
    runs-on: ${{ matrix.os }}
    if: (contains(github.event.pull_request.labels.*.name, 'language-elixir') && contains(github.event.pull_request.labels.*.name, 'scope-semconv'))
    name: Test SemConv on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ["27.2.4", "26.2.5.21"]
        elixir_version: ["1.18.1", "1.14.5"]
        rebar3_version: ["3.24.0"]
        os: [ubuntu-24.04]
        exclude:
          - elixir_version: "1.14.5"
          - otp_version: "27.2.4"
    defaults:
      run:
        working-directory: apps/opentelemetry_semantic_conventions
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}
          rebar3-version: ${{ matrix.rebar3_version }}
          version-type: "strict"
      - name: Cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~/deps
            ~/_build
          key: ${{ runner.os }}-test-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ hashFiles('**/mix.lock') }}

      - name: Get and compile deps
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile
      - name: ExUnit
        run: mix test
