name: "Pull Request Labeler"
on: [pull_request_target]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      pull-requests: write # required for labeling PRs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
